### ISSUE TITLE
 error: 'validator_1.default.isURL is not a function'

### ISSUE THREAD

**Issue by fabianwohlfart** [jshemas/openGraphScraper#233]
We upgraded from 6.5.0 to 6.6.3 and now we get the following error on localhost, didn't test it in prod.

```
await ogs({ url: 'xyz' })

{ error: true,
  result:
   { success: false,
     requestUrl: 'xyz',
     error: 'validator_1.default.isURL is not a function',
     errorDetails:
      TypeError: validator_1.default.isURL is not a function
          at isUrlValid (.../node_modules/open-graph-scraper/dist/esm/lib/utils.js:39:77)
          at validateAndFormatURL (.../node_modules/open-graph-scraper/dist/esm/lib/utils.js:58:19)
          at setOptionsAndReturnOpenGraphResults (.../node_modules/open-graph-scraper/dist/esm/lib/openGraphScraper.js:28:60)
          at run (.../node_modules/open-graph-scraper/dist/esm/index.js:27:55)
          at fetchOpenGraph (...) },
  response: undefined,
  html: undefined }

```

**Comment by jshemas** [comment]
Hello. What version of node are using and what does your `tsconfig.json` look like?

**Comment by fabianwohlfart** [comment]
Hey. It's Node 20.15.1 and the tsconfig.json is auto-generated by Nuxt (https://nuxt.com/docs/guide/directory-structure/tsconfig). I rolled back to 6.5.0 and verified that everything works fine there.

**Comment by jshemas** [comment]
Not sure what Nuxt is. Can you make a example app using Nuxt that demos this problem?

**Comment by fabianwohlfart** [comment]
A JS / Vue framework. But I am more or less sure that it's not all about Nuxt, as ogs works in 6.5.x and breaks in 6.6.x.
Here is a minimal repro: https://github.com/fabianwohlfart/test__ogs

`./app.vue` fetches `/api/ogs` which is located in `./server/api/ogs`
`/api/ogs` is doing `await ogs({ url: "https://nytimes.com" })` and failing due to the error above.

(FYI i am away until next thursday, you might not hear back quickly from me)

Thanks!

**Comment by jshemas** [comment]
Hello! Thank you for the full example! It looks like there is some issues with `validator.js` in ESM. Fix is live in `open-graph-scraper@6.7.0`. Let me know if you have any more issues.

**Comment by Sydney-o9** [comment]
@jshemas watch out - I think your fix is triggering issues on normal flows

![image](https://github.com/user-attachments/assets/02df0fa3-693e-489f-9def-49810e276f7f)

**Comment by jshemas** [comment]
@Sydney-o9 That is not related to this issue. Please open a new issue in the future.

**Comment by fabianwohlfart** [comment]
Thanks for the quick fix!
